In [1]:
import numpy as np

In [2]:
A = np.array([[3, 4, 0], [4, 4, 6], [0, 6, 5]])
A

array([[3, 4, 0],
       [4, 4, 6],
       [0, 6, 5]])

In [3]:
np.triu(A)

array([[3, 4, 0],
       [0, 4, 6],
       [0, 0, 5]])

In [5]:
np.tril(A)

array([[3, 0, 0],
       [4, 4, 0],
       [0, 6, 5]])

array1 = np.array([[10, 8], [3, 5]]) 
運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?

In [9]:
array1 = np.array([[10, 8], [3, 5]]) 
array1_inv=np.linalg.inv(array1)
multi=np.matmul(array1,array1_inv)
print(multi)

[[ 1.00000000e+00  0.00000000e+00]
 [-1.38777878e-17  1.00000000e+00]]


運用上列array計算特徵值、特徵向量?

In [11]:
w, v = np.linalg.eig(array1)
print(w,v)

[13.  2.] [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


運用上列array計算SVD?

In [12]:
u, s, vh = np.linalg.svd(array1)
print(u,s,vh)

[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]] [13.94721714  1.86417116] [[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
